title: "Vishal Patel"
url: "https://chiefvishpat.github.io"
baseurl: "/portfolio"
markdown: kramdown

# Hide the ZIP/TAR download buttons from the default theme
show_downloads: false

github_username: ChiefVishPat
linkedin_username: vishalpatel2003
