title: Vishal Patel
description: Software Engineer â€“ AI, Fintech, and Backend Systems
url: "https://chiefvishpat.github.io"
baseurl: "/portfolio"

theme: jekyll-theme-merlot

# Hide the ZIP/TAR download buttons from the default theme
show_downloads: false

github_username: ChiefVishPat
linkedin_username: vishalpatel2003
