title: Vishal Patel
description: Software Engineer â€“ AI, Fintech, and Backend Systems
url: "https://chiefvishpat.github.io"
baseurl: "/portfolio"

theme: jekyll-theme-minimal

github_username: ChiefVishPat
linkedin_username: vishalpatel2003

nav:
  - name: About
    link: /
  - name: Projects
    link: /projects
  - name: Resume
    link: /resume
