title: Vishal Patel
description: Software Engineer - AI, Fintech, and Software Solutions
url: "https://chiefvishpat.github.io"
baseurl: "/portfolio"

theme: jekyll-theme-minimal

github_username: ChiefVishPat
linkedin_username: vishalpatel2003
show_downloads: false
